### PR TITLE
Do not remove accessory, update logging

### PR DESCRIPTION
**Pull request by shamoon**
part of https://github.com/hjdhjd/homebridge-myq2/issues/38

### CODE REVIEW

**Comment by DMBlakeley** [comment]
Confirmed that change works, however, login attempt keep retrying every 5 seconds. Will MyQ server block user with this frequency?

**Comment by sandeen** [comment]
I was worried about hammering the myq servers as well.  Really not sure what to do about that, other than backing off the interval when login fails?

**Comment by sandeen** [comment]
Thanks for the testing and the PR, agreed that the callback is enough.  Better logging also wise.

**Comment by shamoon** [comment]
I will submit a PR for lengthening the time between login requests like I have in another plugin. It’s no big deal just need to find a second!

**Pull request merged**
